services:
  db:
    image: postgres:15-alpine
    container_name: reserva_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: reserva_salas
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: reserva_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - db

  api:
    build: .
    container_name: reserva_api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://admin:adminpassword@db:5432/reserva_salas?schema=public"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: reserva_frontend
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  pgdata: